---
server:  port: 8082
spring:
  application:
    name: alexa-oms

  thymeleaf:
    cache: false
  datasource:    
      url: jdbc:mysql://localhost:3306/alexa_oms?useSSL=false&serverTimezone=US/Eastern&allowPublicKeyRetrieval=true
      username: root
      password: 12345
      driver-class-name: com.mysql.cj.jdbc.Driver
      tomcat:
        initial-size: 2        
        #max-idle: 2        
        max-active: 2
        #min-idle:  2
      
  jpa:
      #database-platform:      org.hibernate.dialect.MySQLInnoDBDialect
      database: MYSQL
      generate-ddl: true
      hibernate:
        ddl-auto: update      
        naming:
          strategy: org.hibernate.cfg.DefaultNamingStrategy
      show-sql: true
 
security:
  ignored: /alexaOms
    
  basic:
    enabled: false 
  oauth2:    
    client:
      client-id: alexa
      client-secret: alexa_secret
     # access-token-validity-seconds: 1800
     # refresh-token-validity-seconds: 1800
     # scope: read, write
     # grant-type: implicit
     # authorized-grant-types: implicit
     # authorities: ROLE_USER
          
 
logging:
  level:
    org.hibernate.type: trace
    com.alexa.oms: trace
    org.springframework.security: debug
    
application:
  id: ${amznAppID:amzn1.ask.skill.bf1cd3c3-0b00-4ca4-b92b-68276106ba56}

      